project: example
seed: 1
version: 1
wandb:
  args:
    reinit: True
  watch:
    log: null
dataloader:   
  name: VolumetricDataLoader
  file_format: tif
  is_distributed: False
  num_workers: 16
  patch_size: 64
  training:
    batch_size: 5
    patches_per_volume: 2000
    queue_length: 1000
    sampling: sampling_likelihood
    data_augm_v: 4
    dataset:
      path:                /data/example/trainset/image
      label:               /data/example/trainset/label
      sampling_likelihood: /data/example/trainset/sampling_likelihood # can be removed if 'uniform' or 'label' sampling is used
  validation:
    batch_size: 5
    patches_per_volume: 2000
    queue_length: 500
    sampling: sampling_likelihood
    dataset:
      path:                /data/example/valset/image
      label:               /data/example/valset/label
      sampling_likelihood: /data/example/valset/sampling_likelihood 
  test_and_predict:
    batch_size: 5
    patch_overlap: 32 #32
    dataset:
      path:    /data/example/test/image
      label:   /data/example/test/label
      results: /data/example/test/predictions
  test: # can be deleted if no post-processing is used
    post_processing:
      - module: imagetools.basic_operations # imagetools is a fictitious module that is in the PYTHONPATH, which contain a function called complement_to_one_API in the submodule basic_operations
        fun: complement_to_one_API
        forward_arrays: y_hat # arrays in the test_step() or predict_step() of the model that will be passed to the function for post-processing
  predict: # can be deleted if no post-processing is used
    post_processing:
      - module: imagetools.pore_segmentation
        fun: pore_segmentation
        forward_arrays: y_hat
        threshold: otsu
        is_background_zero_centered: True
model:
  name: ACC-Unet-example
  type: models.ACC_Unet
  compiled: True
  n_channels: 1
  n_classes: 1
  depth: 4
  n_filts: 16
  padding: 1
  dropout: 0.1
  loss: 
    name: torch_focal_tversky_loss
    parameters:
      gamma: 1.
      alpha: 0.633
      beta: 0.1
  evaluate_metrics:
    validation:
      - name: torch_dice
  checkpoint_path: /data/example/checkpoints/
  log_path: /data/example/logs/
  activation: leakyrelu
  last_activation: sigmoid
  optimizer: Adam
  optimizer_parameters:
    lr: 0.0001
training:
  args:
    #replace_sampler_ddp: False
    max_epochs: 200
    precision: 32
    accumulate_grad_batches: 8
    num_sanity_val_steps: 2
    accelerator: gpu
    devices: 1
  callbacks:
    early_stopping:
      monitor: Train/loss
      strict: True
      min_delta: 1.e-3
      patience: 40
      verbose: False
      mode: min
      log_rank_zero_only: True
  #checkpoint: "/home/diuso/Projects/nn/checkpoints/main_studysimple-Unet-epoch=159.ckpt"
test_and_predict:
  args:
    max_epochs: -1
    accelerator: gpu
    devices: 1
  checkpoint: last