project: example
seed: 1
version: 1
wandb:
  args:
    reinit: True
  watch:
    log: null
dataloader:   
  name: VolumetricDataLoader
  file_format: tif
  is_distributed: False
  num_workers: 16
  patch_size: 64
  aggregate_patches: True
  training:
    batch_size: 100
    patches_per_volume: 4000
    queue_length: 4000
    sampling: uniform
    data_augm_v: 4
    dataset:
      path:                /data/example/trainset/image
      label:               /data/example/trainset/label
      sampling_likelihood: /data/example/trainset/sampling_likelihood # can be removed if 'uniform' or 'label' sampling is used
  validation:
    batch_size: 100
    patches_per_volume: 1000
    queue_length: 1000
    sampling: uniform
    dataset:
      path:                /data/example/valset/image
      label:               /data/example/valset/label
      sampling_likelihood: /data/example/valset/sampling_likelihood 
  test_and_predict:
    batch_size: 100
    patch_overlap: 32
    dataset:
      path:    /data/example/test/image
      label:   /data/example/test/label
      results: /data/example/test/predictions
  test: # can be deleted if no post-processing is used
    post_processing:
      module: nn.utils.utils
      fun: suppress_borders_and_outside_with_optimization_torch_hook
      pars: [ 2.4328547425, 5.98152321]
      forward_arrays:  [y_hat, rec_error]
      forward_devices: [cuda:1, cuda:1]
  predict:
    post_processing:
      module: nn.utils.utils
      fun: suppress_borders_and_outside_with_optimization_torch_hook
      pars: [ 2.4328547425, 5.98152321]
      forward_arrays:  [y_hat, rec_error]
      forward_devices: [cuda:1, cuda:1]
model:
  name: RV_VAE-example
  type: models.RV_VAE
  log_wandb_images: True
  compiled: False
  n_channels: 1
  n_classes: 1
  input_size: 64
  kernel_size: 3
  channel_depths: [32, 64, 128, 256, 1024]
  padding: 1
  dropout:   [null,null,null,null,null] # [0.05, 0.05, 0.05, null, null] #[null, null, null, null, null, null, null]
  batch_norm: null #[null, null, null, null, null, null, null]
  insta_norm: null #[True, null, null, null, null, null, null]
  loss: 
    name: RV_VAE_loss
    parameters:
      kl_weight: 1.e-5
      var_weight: 50
  evaluate_metrics:
    validation:
    - name: rv_torch_dice_loss
    test:
      #- name: torch_dice
      name: pore_segmentation_curves
      parameters:
          #bins: 100
          device: 'cuda:1'
          slices: [70,1000,70,1000,100,900]
          pred_mask: False
  checkpoint_path: /data/example/checkpoints/
  log_path: /data/example/logs/
  activation: relu
  last_activation: sigmoid #sigmoid
  optimizer: Adam
  optimizer_parameters:
    lr: 0.0001
training:
  args:
    #replace_sampler_ddp: False
    max_epochs: 300
    precision: 32
    detect_anomaly: False
    accumulate_grad_batches: 4
    num_sanity_val_steps: 2
    accelerator: gpu
    devices: 1
  callbacks:
    early_stopping:
      monitor: Train/loss
      strict: True
      min_delta: 1.e-3
      patience: 40
      verbose: False
      mode: min
      log_rank_zero_only: True
  #checkpoint: last
test_and_predict:
  args:
    max_epochs: -1
    accelerator: gpu
    devices: 1
  checkpoint: last